apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: d3344c80-3a36-42a7-a127-f0454ee05e94
          target-environment: TOTO
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: eafb141d-224c-4164-a95c-12fb7fa2a549
          target-environment: Test_env