apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: eafb141d-224c-4164-a95c-12fb7fa2a549
          target-environment: TOTO
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: 4008353e-d30b-44f2-b765-ddd06a1d5304
          target-environment: Test_env